modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gentlefawn"
version="${file.jarVersion}"
displayName="Gentle Fawn"
authors="sakiraart & gdude2002"
description='''
It's literally just deer.
'''

[[dependencies.gentlefawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
