modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)

[[mods]] #mandatory

modId="gentlefawn"
version="${file.jarVersion}"
displayName="Gentle Fawn"
authors="sakiraart & gdude2002"
description='''
It's literally just deer.
'''

[[dependencies.gentlefawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
